version: '{build}'
os: Windows Server 2012
install:
  - ps: iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
  - ps: scoop install sbt
  - ps: $env:SBT_OPTS="-XX:MaxPermSize=2g -Xmx4g"
  - ps: $env:CLANG_PATH="C:\\Program Files\\LLVM\\bin\\clang.exe"
  - ps: $env:CLANGPP_PATH="C:\\Program Files\\LLVM\\bin\\clang++.exe"
  - ps: $env:CLANG_FORMAT_PATH="C:\\Program Files\\LLVM\\bin\\clang-format.exe"
  - ps: $env:JAVA_TOOL_OPTIONS="-Dfile.encoding=UTF8"
  - ps: $env:JAVA_OPTS="-Xmx2G"
  - ps: .\bin\scalafmt --install
  - ps: .\bin\coursier.ps1 bootstrap com.geirsson:scalafmt-cli_2.11:0.6.8 --main org.scalafmt.cli.Cli -o .\bin\scalafmt-CI-0.6.8.jar -f
build_script:
  - ps: |
        if ($env:APPVEYOR_PULL_REQUEST_NUMBER) {
            Write-Output "Incoming pull request from https://github.com/$env:APPVEYOR_REPO_SLUG/pull/$env:APPVEYOR_PULL_REQUEST_NUMBER";
            $authorReq= try { Invoke-RestMethod -UseDefaultCredentials -Uri "https://api.github.com/repos/$env:APPVEYOR_REPO_SLUG/pulls/$env:APPVEYOR_PULL_REQUEST_NUMBER" -ErrorVariable RestError -ErrorAction SilentlyContinue} catch { $RestError.message | ConvertFrom-Json};
            $author = $authorReq.user.login;
            if ($author) {
                Write-Output "Pull request submitted by $author";
                $signedReq=try { Invoke-RestMethod -Uri "http://www.lightbend.com/contribute/cla/scala/check/$author" -ErrorVariable RestError -ErrorAction SilentlyContinue} catch { $RestError.message | ConvertFrom-Json};
                if ($signedReq.signed -eq "true") {
                    Write-Output "CLA check for $author successful";
                }
                else {
                    Write-Output "CLA check for $author failed";
                    Write-Output "Please sign the Scala CLA to contribute to Scala Native";
                    Write-Output "Go to https://www.lightbend.com/contribute/cla/scala and then resubmit this pull request";
                    exit 1;
                } else {exit 1};
            } else {exit 1};
        }
test_script:
  - ps: .\bin\scalafmt --test
  - ps: .\bin\clangfmt --test  
  - ps: sbt rebuild
  - ps: sbt "set scriptedBufferLog in sbtScalaNative := false" test-all
cache:
  - C:\Users\appveyor\.m2
  - C:\Users\appveyor\.ivy2
  - C:\Users\appveyor\.coursier